---
type: showroom

# Set the left column width to 30%
default_width: 40
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: OpenShift Console
    url: 'https://console-openshift-console.${DOMAIN}'

  - name: Terminal
    port: 443
    path: /terminal

  - name: Keycloak
    url: 'https://etx-sso.${DOMAIN}'

  - name: Argo CD
    url: 'https://argocd-server-etx-app-dev.${DOMAIN}'

  - name: GitLab
    url: 'https://gitlab.${DOMAIN}'

  - name: Quay
    url: 'https://quay.${DOMAIN}'

  - name: Developer Hub
    url: 'https://backstage-rhdh-setup-rhdh.${DOMAIN}'

  - name: Vault
    url: 'https://vault.${DOMAIN}'
